export const MAIN_BUTTON = ['LAMP TEST', 'BUZZER MUTE', 'BATTERY TEST', 'MASTER RESET'];
export const SMOKE_DET_BUTTON = ['TEST FIRE', 'TEST FAULT', 'ISOLATE'];
export const HEAT_DET_BUTTON = ['TEST FIRE', 'TEST FAULT', 'ISOLATE'];
export const DISCHARGE_BUTTON = ['ISOLATE SWITCH'];
export const ON_OFF_BUTTON = ['ON', 'OFF']