export const POWER_LIST = ['MAINS ON', 'BATTERY ON', 'SYSTEM ON'];
export const GENERAL_LIST = ['GENERAL ALARM', 'GENERAL FAULT'];
export const MAIN_FAILURE_LIST = ['MAINS/FUSE FAIL', 'CHARGER FAIL', 'BATTERY FAIL', 'EARTH FAULT', 'FAP ISOLATE', 'BELL ISOLATE'];
export const SMOKE_DET_LIST = ['FIRE', 'FAULT', 'ISOLATE'];
export const HEAT_DET_LIST = ['FIRE', 'FAULT', 'ISOLATE'];
export const DISCHARGE_LIST = ['GAS DISCHARGE', 'DISC. LINE FAULT', 'LOW PRESSURE', 'GAS ISOLATE'];